language: node_js
node_js:
  - "10"
cache:
  yarn: true
  directories:
    - node_modules
    - lighthouse-plugin-publisher-ads/node_modules
branches:
  only:
    - master
install:
  - yarn install --frozen-lockfile
script:
  - yarn lint
  - yarn test
  - yarn type-check
before_cache:
  - rm -rf ./node_modules/.cache/
  - rm -rf lighthouse-plugin-publisher-ads/node_modules/.cache/
